/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { IMyERC20 } from "./IMyERC20";
export type { IMyERC721 } from "./IMyERC721";
export type { TokenSale } from "./TokenSale";
